package edu.washington.cs.rtrefactor.detect;

import java.io.File;

import org.eclipse.jface.text.BadLocationException;
import org.eclipse.jface.text.IDocument;

/**
 * A location in a source file. 
 * Stores two representations: line and offset in that line or global offset 
 * 		into the file.
 *   
 * @author Todd Schiller
 * @author Travis Mandel
 */
public class SourceLocation implements Comparable<SourceLocation>{

	private File file;
	private int line;
	private int lineOffset;
	private int globalOffset;

	/**
	 * Construct a record describing a location in a source file, given
	 * the line and line specific offset.  
	 * 
	 * Performs and stores the conversion to global offset form. 
	 * 
	 * @param file the source file, or file underlying the buffer (non-null)
	 * @param line the line number (<code>0 <= line <= document.getNumberOfLines()</code>)
	 * @param lineOffset the offset on the line (>= 0)
	 * @param document the source document buffer (non-null)
	 * @throws BadLocationException If line/offset is not a valid location 
	 * 		in the document 
	 */
	public SourceLocation(File file, int line, int lineOffset, IDocument document) throws BadLocationException {
		super();
		if (file == null){
			throw new NullPointerException("Attempt to create source location with no associated source file");
		}else if (line < 0){
			throw new IllegalArgumentException("Attempt to create source location with a negative line number");
		}else if (lineOffset < 0){
			throw new IllegalArgumentException("Attempt to create source location with a negative line offset");	
		}else if (document == null){
			throw new NullPointerException("Attempt to create source location with no associated source document");
		}

		this.file = file;
		this.line = line;
		this.lineOffset = lineOffset;
		convertLineOffset(document);
	}

	/**
	 * Construct a record describing a location in a source file, given the global 
	 * 	offset into the file.
	 * 
	 * Performs and stores the conversion to line-offset form.
	 * 
	 * @param file the source file, or file underlying the buffer (non-null)
	 * @param globalOffset the global offset in the file (<code>0 <= globalOffset <= document.getLength()</code>)
	 * @param document the source document buffer (non-null)
	 * @throws BadLocationException If global offset is not a valid location in 
	 * 		the document 
	 */
	public SourceLocation(File file, int globalOffset, IDocument document) throws BadLocationException {
		super();

		if (file == null){
			throw new NullPointerException("Attempt to create source location with no associated source file");
		}else if (document == null){
			throw new NullPointerException("Attempt to create source location with no associated source document");
		}else if (globalOffset < 0){
			throw new BadLocationException("Attempt to create source location with a negative global offset");	
		}else if (globalOffset > document.getLength()){
			throw new BadLocationException(
					"Attempt to create source location with global offset beyond the end of the document " +
					"(offset: " + globalOffset + ", len: " + document.getLength() + ")");
		}

		this.file = file;
		this.globalOffset = globalOffset;
		convertGlobalOffset(document);
	}

	/**
	 * get the source file, or the file underlying the buffer
	 * @return the source file, or the file underlying the buffer
	 */
	public File getFile() {
		return file;
	}

	/**
	 * get the the line number
	 * @return the line number
	 */
	public int getLine() {
		return line;
	}

	/**
	 * get the offset on the line
	 * @return the offset on the line
	 * @see getLine
	 */
	public int getLineOffset() {
		return lineOffset;
	}

	/**
	 * get the offset in the file
	 * @return the offset in the file
	 * @see getLine
	 */
	public int getGlobalOffset() {
		return globalOffset;
	}


	@Override
	public int compareTo(SourceLocation o) {
		if (o == null){
			throw new NullPointerException("Attempt to compare source location to null");
		}else if(!file.equals(o.file)){
			throw new IllegalArgumentException("Cannot compare source locations with different underlying files");
		}

		return new Integer(globalOffset).compareTo(o.globalOffset);
	}

	/// AUTOGENERATED hashCode() and equals() functions
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((file == null) ? 0 : file.hashCode());
		result = prime * result + globalOffset;
		result = prime * result + line;
		result = prime * result + lineOffset;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SourceLocation other = (SourceLocation) obj;
		if (file == null) {
			if (other.file != null)
				return false;
		} else if (!file.equals(other.file))
			return false;
		if (globalOffset != other.globalOffset)
			return false;
		if (line != other.line)
			return false;
		if (lineOffset != other.lineOffset)
			return false;
		return true;
	}


	/**
	 * Given a document, computed and stores this location's
	 * global offset based on its line and line offset
	 * 
	 * @param doc The document which this SourceLocation is in
	 */
	private void convertLineOffset(IDocument doc) throws BadLocationException
	{
		int off = (line == 0) ? 0 : doc.getLineOffset(line-1);
		this.globalOffset = off + lineOffset;
	}

	/**
	 * Given a document, compute this location's line and offset based on
	 * its global offset
	 * 
	 * @param doc the document this SourceLocation is in
	 */
	private void convertGlobalOffset(IDocument doc) throws BadLocationException
	{
		this.line = doc.getLineOfOffset(globalOffset);
		int lineOff = (line == 0) ? 0 : doc.getLineOffset(line - 1);
		this.lineOffset = globalOffset - lineOff;
	}
	
	
}